export const themes = {
  Light: {
    name: 'Light',
    background: '#ffffff',
    navBarBackground: '#f0f0f0',
    navBarTextColor: '#343a40',
    buttonBackground: '#b0bec5',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#78909c',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#495057',
    inputBorderColor: '#ced4da',
    headerBackground: '#f3f4f6',
    headerTextColor: '#212529',
    modalBackground: '#f7f7f7',
    modalTextColor: '#495057',
    border: '#dee2e6',
    scrollBarThumb: '#adb5bd',
    scrollBarTrack: '#f8f9fa',
    chartColors: ['#b0bec5', '#78909c', '#cfd8dc', '#90a4ae'],
  },
  Dark: {
    name: 'Dark',
    background: '#1b1b1b',
    navBarBackground: '#333333',
    navBarTextColor: '#e4e6eb',
    buttonBackground: '#444444',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#555555',
    buttonHoverTextColor: '#222222',
    inputBackground: '#2c2c2c',
    inputTextColor: '#e4e6eb',
    inputBorderColor: '#555555',
    headerBackground: '#3b3b3b',
    headerTextColor: '#f1f1f1',
    modalBackground: '#262626',
    modalTextColor: '#d3d3d3',
    border: '#444444',
    scrollBarThumb: '#606060',
    scrollBarTrack: '#2e2e2e',
    chartColors: ['#66bb6a', '#29b6f6', '#ef5350', '#ffca28'],
  },
  Green: {
    name: 'Green',
    background: '#e8f5e9',
    navBarBackground: '#66bb6a',
    navBarTextColor: '#ffffff',
    buttonBackground: '#388e3c',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#2e7d32',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#2e7d32',
    inputBorderColor: '#a5d6a7',
    headerBackground: '#c8e6c9',
    headerTextColor: '#1b5e20',
    modalBackground: '#dcedc8',
    modalTextColor: '#2e7d32',
    border: '#a5d6a7',
    scrollBarThumb: '#66bb6a',
    scrollBarTrack: '#e8f5e9',
    chartColors: ['#388e3c', '#66bb6a', '#81c784', '#a5d6a7'],
  },
  Blue: {
    name: 'Blue',
    background: '#e3f2fd',
    navBarBackground: '#42a5f5',
    navBarTextColor: '#ffffff',
    buttonBackground: '#1e88e5',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#1565c0',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#1565c0',
    inputBorderColor: '#90caf9',
    headerBackground: '#bbdefb',
    headerTextColor: '#0d47a1',
    modalBackground: '#e1f5fe',
    modalTextColor: '#1565c0',
    border: '#90caf9',
    scrollBarThumb: '#42a5f5',
    scrollBarTrack: '#e3f2fd',
    chartColors: ['#1e88e5', '#42a5f5', '#90caf9', '#bbdefb'],
  },
  Red: {
    name: 'Red',
    background: '#ffebee',
    navBarBackground: '#ef5350',
    navBarTextColor: '#ffffff',
    buttonBackground: '#e53935',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#c62828',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#c62828',
    inputBorderColor: '#ef9a9a',
    headerBackground: '#ffcdd2',
    headerTextColor: '#b71c1c',
    modalBackground: '#ffebee',
    modalTextColor: '#c62828',
    border: '#ef9a9a',
    scrollBarThumb: '#ef5350',
    scrollBarTrack: '#ffebee',
    chartColors: ['#e53935', '#ef5350', '#ff7043', '#ff8a65'],
  },
  Purple: {
    name: 'Purple',
    background: '#f3e5f5',
    navBarBackground: '#8e24aa',
    navBarTextColor: '#ffffff',
    buttonBackground: '#ab47bc',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#7b1fa2',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#4a148c',
    inputBorderColor: '#ce93d8',
    headerBackground: '#e1bee7',
    headerTextColor: '#6a1b9a',
    modalBackground: '#f3e5f5',
    modalTextColor: '#6a1b9a',
    border: '#ce93d8',
    scrollBarThumb: '#8e24aa',
    scrollBarTrack: '#f3e5f5',
    chartColors: ['#ab47bc', '#ce93d8', '#ba68c8', '#8e24aa'],
  },
  Teal: {
    name: 'Teal',
    background: '#e0f7fa',
    navBarBackground: '#00897b',
    navBarTextColor: '#ffffff',
    buttonBackground: '#00796b',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#004d40',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#004d40',
    inputBorderColor: '#80cbc4',
    headerBackground: '#b2dfdb',
    headerTextColor: '#004d40',
    modalBackground: '#e0f2f1',
    modalTextColor: '#004d40',
    border: '#80cbc4',
    scrollBarThumb: '#00897b',
    scrollBarTrack: '#e0f7fa',
    chartColors: ['#00796b', '#00897b', '#4db6ac', '#80cbc4'],
  },
  Orange: {
    name: 'Orange',
    background: '#fff3e0',
    navBarBackground: '#ff7043',
    navBarTextColor: '#ffffff',
    buttonBackground: '#ff5722',
    buttonTextColor: '#ffffff',
    buttonHoverBackground: '#e64a19',
    buttonHoverTextColor: '#ffffff',
    inputBackground: '#ffffff',
    inputTextColor: '#bf360c',
    inputBorderColor: '#ffab91',
    headerBackground: '#ffe0b2',
    headerTextColor: '#bf360c',
    modalBackground: '#ffccbc',
    modalTextColor: '#d84315',
    border: '#ffab91',
    scrollBarThumb: '#ff7043',
    scrollBarTrack: '#fff3e0',
    chartColors: ['#ff5722', '#ff7043', '#ff8a65', '#ffab91'],
  },
};

export const getTheme = (themeName) => themes[themeName] || themes.Light;
